---
- name: restart docker
  command: /bin/true
  notify:
    - reload systemd
    - reload docker
    - wait for docker
    - docker is ready

- name: reload systemd
  command: systemctl daemon-reload

- name: reload docker
  service:
    name: docker
    state: restarted

- name: wait for docker
  pause:
    seconds: 10
    prompt: "Wait a little before docker start"

- name: docker is ready
  command: "/usr/bin/docker images"
  register: docker_ready
  retries: 10
  delay: 5
  until: docker_ready.rc == 0
